### ISSUE TITLE
Status of the library

### ISSUE THREAD

**Issue by Antondomashnev** [railsware/BloodMagic#37]
Hi there, thanks first of all for such a framework. I see that the last changes were done for a while ago, so is this still production usable or not? 😄

**Comment by AlexDenisov** [comment]
Hi, thank you for your kind words.

The initial idea was to save time by adding some magic so that a developer can save few lines of code. It works just perfect for a short distance but can be harmful in a long running project.

Technically it should work fine, even though I didn't touch it for a while, neither I used it for a couple of years.

However, over time I've got few reports when the library didn't shine: people used it in a way that I didn't expect them to use it. That said, I suggest you weighing all pros and cons and make the decision based on your use case rather on usability if a particular library.

**Comment by Antondomashnev** [comment]
@AlexDenisov thanks for the response, it's really helpful 👍
